// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID           int64
	Name         string
	ParentID     pgtype.Int8
	SpecTemplate json.RawMessage
	Sort         int32
	CreatedAt    pgtype.Timestamp
}

type ProductSku struct {
	ID        int64
	SpuID     int64
	Price     pgtype.Numeric
	Stock     int32
	Specs     json.RawMessage
	CreatedAt pgtype.Timestamp
}

type ProductSpu struct {
	ID          int64
	Name        string
	Description pgtype.Text
	CategoryID  int64
	CreatedAt   pgtype.Timestamp
}
